### Get All administrators
GET http://localhost:8080/academics/api/administrators
Accept: application/json

### REQUEST JWT TOKEN
POST http://localhost:8080/academics/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "admin", "password": "123" }

### Get authenticated user (replace <JWT_TOKEN> with the token returned above)
GET http://localhost:8080/academics/api/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2NzMwNDg3MSwiZXhwIjoxNzY3MzA4NDcxfQ.j1SZ6typCIwYRI_RlyQH853Jq4WKqpWtvECHN5T9UjAi4B5G97u6UIeHBw1AOybI


### refresh token
POST http://localhost:8080/academics/api/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2NTk5MzYyMywiZXhwIjoxNzY1OTk3MjIzfQ.sjKL_mzYJP_nzLPXerCEmCvyulcXN6o5JukGEUlxgsSJ47x6JV2DdD0AUMusJ0vB

### SET NEW PASSWORD
PATCH http://localhost:8080/academics/api/auth/set-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2NTk5MzYyMywiZXhwIjoxNzY1OTk3MjIzfQ.sjKL_mzYJP_nzLPXerCEmCvyulcXN6o5JukGEUlxgsSJ47x6JV2DdD0AUMusJ0vB

{
  "oldPassword": "123",
  "newPassword": "1234",
  "confirmPassword": "1234"
}

### RECOVER PASSWORD
POST http://localhost:8080/academics/api/auth/recover-password
Content-Type: application/json
Accept: application/json

{
  "email": "banana@example.com"
}

### RESET PASSWORD
PUT http://localhost:8080/academics/api/auth/reset-password
Content-Type: application/json

{
  "token": "550e8400-e29b-41d4-a716-446655440000",
  "nova_password": "1234"
}

### Create User (Administrator only)
POST http://localhost:8080/academics/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2NzM1MDY0OSwiZXhwIjoxNzY3MzU0MjQ5fQ.4-8zG2v596iO9pbsDyzTL0Ukjlwp0xZ2uBED5e_-ARlAgl0c1MoFiKF1Z-OKc8TQ


{
  "name": "João Silva",
  "username": "joao",
  "password": "joaosilva2003",
  "role": 3,
  "email": "joao.silva@gmail.com",
  "active": true
}


### Update User (Administrator only)
PUT http://localhost:8080/academics/api/users/joao
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2NzM1MDY0OSwiZXhwIjoxNzY3MzU0MjQ5fQ.4-8zG2v596iO9pbsDyzTL0Ukjlwp0xZ2uBED5e_-ARlAgl0c1MoFiKF1Z-OKc8TQ


{
  "username": "joao",
  "email": "joao.silva@gmail.com",
  "active": false
}





### Create A New Student
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
  "email": "johndoe@mail.com",
  "name": "John Doe",
  "username": "john",
  "password": "jd",
  "courseCode": 1
}

### Get All Courses
GET http://localhost:8080/academics/api/courses
Accept: application/json

### Create A New Course
POST http://localhost:8080/academics/api/courses
Content-Type: application/json

{
  "code": 3,
  "name": "TAES"
}

### Get A Single Student
GET http://localhost:8080/academics/api/students/buro
Accept: application/json

### Get Student Subjects
GET http://localhost:8080/academics/api/students/buro/subjects
Accept: application/json


### Alternative (.http file)
POST http://localhost:8080/academics/api/students/buro/email
Content-Type: application/json

{
  "subject": "Test subject",
  "body": "This is a test email body."
}



### GET ALL STUDENTS
GET http://localhost:8080/academics/api/students
Accept: application/json
Authorization: Bearer <eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbjEiLCJpYXQiOjE3NjIzOTM0MDYsImV4cCI6MTc2MjM5NzAwNn0.TgbasV_mzErHD_aIUfdKwR-wJ3_XMI0lCzIlhNjkBhglHC-h5xjr8n0yQoWmzg3z>













