
### Get All administrators
GET http://localhost:8080/academics/api/administrators
Accept: application/json

### SET NEW PASSWORD
PATCH http://localhost:8080/academics/api/auth/set-password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "oldPassword": "123",
  "newPassword": "1234",
  "confirmPassword": "1234"
}

### RECOVER PASSWORD
POST http://localhost:8080/academics/api/auth/recover-password
Content-Type: application/json
Accept: application/json

{
  "email": "banana@example.com"
}

### RESET PASSWORD
PUT http://localhost:8080/academics/api/auth/reset-password
Content-Type: application/json

{
  "token": "550e8400-e29b-41d4-a716-446655440000",
  "nova_password": "1234"
}

### Create User (Administrator only)
POST http://localhost:8080/academics/api/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}


{
  "name": "João Silva",
  "username": "joao",
  "password": "joaosilva2003",
  "role": 3,
  "email": "joao.silva@gmail.com",
  "active": true
}


### Update User (Administrator only)
PUT http://localhost:8080/academics/api/users/joao
Content-Type: application/json
Authorization: Bearer {{auth_token}}


{
  "username": "joao",
  "email": "joao.silva@gmail.com",
  "active": false
}

### Get Users
GET http://localhost:8080/academics/api/users
Accept: application/json
Authorization: Bearer {{auth_token}}

### Delete User (Administrator only)
DELETE http://localhost:8080/academics/api/users/joao
Authorization: Bearer {{auth_token}}

### Suspend User (Administrator only)
PATCH http://localhost:8080/academics/api/users/joao/status
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "active": false,
  "motive": "Violação das políticas de utilização"
}

### Activate User (Administrator only)
PATCH http://localhost:8080/academics/api/users/joao/status
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "active": true
}

### Update User Role (Administrator only)
PATCH http://localhost:8080/academics/api/users/joao/role
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "role": 2
}

### Get All Users (Administrator only)
GET http://localhost:8080/academics/api/users
Accept: application/json
Authorization: Bearer {{auth_token}}


### Get User by Username (Administrator only)
GET http://localhost:8080/academics/api/users/joao
Accept: application/json
Authorization: Bearer {{auth_token}}



